language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7

addons:
    apt:
        packages:
            - fontconfig
            - inkscape
            - dvipng
            - texlive
            - texlive-latex-extra
            - python-tk
            - xvfb

services:
    - xvfb

cache:
    pip: true

before_install:
    - sudo apt-get update -qq
    - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
    - sudo apt-get install -qq msttcorefonts ttf-mscorefonts-installer
    - sudo fc-cache -vf

install:
    - pip install tox
    - pip install coveralls

before_script:
    # See https://github.com/tox-dev/tox/issues/318
    - export TOXENV=`tox --listenvs | grep $(echo py${TRAVIS_PYTHON_VERSION}- | tr -d . | sed -e 's/pypypy/pypy/') | tr '\n' ','`

script:
    - tox

after_success:
    - coveralls

