name: test

on:
  push:
    branches: [ master, testing ]
    paths-ignore:
    - 'README*'
    - 'LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'README*'
    - 'LICENSE'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Enable tmate debugging (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['2.7', '3.6', '3.7', '3.8', '3.9']
        include:
          - os: ubuntu-18.04
            python-version: '3.4'
          - os: ubuntu-18.04
            python-version: '3.5'

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get update -qq
        # install fonts.
        sudo apt-get install -qq fontconfig
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get install -qq msttcorefonts ttf-mscorefonts-installer
        sudo fc-cache -vf
        # install format converters.
        sudo apt-get install -qq inkscape ghostscript dvipng
        # install tex.
        sudo apt-get install -qq texlive texlive-latex-extra
        # install x server.
        sudo apt-get install -qq python-tk xvfb
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox coverage
    - name: Fix issue with matplotlib 1.4
      # avoid an issue in distutil when installing matplotlib 1.4.
      # see https://stackoverflow.com/a/27085321
      run: |
        sudo apt-get install -qq libfreetype6-dev
      if: ${{ matrix.os == 'ubuntu-18.04' }}
    - name: Select tests
      run: |
        TOXENV=$(tox --listenvs | grep $(echo "py${{ matrix.python-version }}-" | tr -d . | sed -e "s/pypypy/pypy/") | tr "\n" ",")
        echo $TOXENV
        echo "TOXENV=$TOXENV" >> $GITHUB_ENV
    - name: Test
      run: |
        xvfb-run --auto-servernum tox
    - name: Setup tmate session if enabled debugging
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      with:
        limit-access-to-actor: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      timeout-minutes: 60
    - uses: bcomnes/cleanup-xvfb@v1
    - name: Upload coverage data
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true

